- name: SSH Application Deploy
  uses: appleboy/ssh-action@master
  with:
    host: ${{ env.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
    script: |
      sudo yum update -y
      if [ -f /etc/systemd/system/StudentManagement.service ]; then
        echo "already exists Service File"
      else
        cat <<EOL | sudo tee /etc/systemd/system/StudentManagement.service
        [Unit]
        Description=StudentManagement App
      
        [Service]
        ExecStart=java -jar ${DEST_PATH}
        EnvironmentFile=/etc/sysconfig/StudentManagement
        Restart=no
        Type=simple
        User=ec2-user
        Group=ec2-user
        SuccessExitStatus=143
      
        [Install]
        WantedBy=multi-user.target
  EOL
  fi
  
  sudo systemctl daemon-reload
if sudo systemctl status StudentManagement 2>&1 | grep "Active: active (running)" ; then
  sudo systemctl restart StudentManagement
  else
  sudo systemctl start StudentManagement
  fi
